<a href="https://colab.research.google.com/github/YadiraMed/practica/blob/main/NumPy_Exercises_for_Data_Analysis_YadiraMedranda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importe numpy como np y vea la versión

In [ ]:
import numpy as np
np. __version__

'1.22.4'

Crear una matriz 1D de números del 0 al 9

In [ ]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(array)

[1 2 3 4 5 6 7 8 9]


Cree una matriz numpy de 3 × 3 de todos los True

In [ ]:
array = np.ones((3, 3), dtype=bool)
print(array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


Extrae todos los números impares de la matriz

In [ ]:
odd_numbers = array[array % 2 != 0]
print(odd_numbers)

[1 3 5 7 9]


Reemplace todos los números impares en la matriz con -1

In [ ]:
array[array % 2 != 0] = -1
print(array)

[-1  2 -1  4 -1  6 -1  8 -1]


Convierta una matriz 1D en una matriz 2D con 2 filas

In [ ]:
matriz1d= np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
matriz2d = matriz1d.reshape(2, -1)
print(matriz2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


Apilar matrices a y b verticalmente

In [ ]:
A = np.array([1, 2, 3, 4, 5])
B = np.array([6, 7, 8, 9, 10])

stacked = np.vstack((A, B))
print(stacked)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


Apila las matrices a y b horizontalmente

In [ ]:
A = np.array([1, 2, 3, 4, 5])
B = np.array([6, 7, 8, 9, 10])

stacked = np.hstack((A, B))
print(stacked)

[ 1  2  3  4  5  6  7  8  9 10]


Obtenga todos los artículos entre 5 y 10 de a.

In [ ]:
a = np.arange(15)
print(a[5:11])

[ 5  6  7  8  9 10]


¿Cómo hacer una función de python que maneje escalares para trabajar en matrices numpy?

In [109]:
def suma_escalar(matriz, escalar):
    resultado = np.add(matriz, escalar)
    return resultado
    a = np.array([5, 7, 9, 8, 6, 4, 5])
    b = np.array([6, 3, 4, 8, 9, 7, 1])

resultado = suma_escalar(a, b)
print(resultado)

[11 10 13 16 15 11  6]


Intercambiar las columnas 1 y 2 en la matriz

In [127]:
matriz = np.array([[4, 5, 1], [2, 3, 7], [6, 8, 9]])
matriz[:, [1, 2]] = matriz[:, [2, 1]]
print(matriz)

[[4 1 5]
 [2 7 3]
 [6 9 8]]


Cree una matriz 2D de forma 5x3 para contener números decimales aleatorios entre 5 y 10.

In [128]:
matriz = np.random.uniform(5, 10, size=(5, 3))
print(matriz)

[[7.52977131 9.28098118 7.70415372]
 [6.02204294 5.94767539 6.68980197]
 [9.04999598 8.04138965 7.73361795]
 [7.81714494 8.31182333 6.65276357]
 [5.71429554 5.8194423  7.20219942]]
